// <auto-generated />
using System;
using CarAuction.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAuction.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarAuctionContext))]
    [Migration("20240805105332_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartingBid")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Vehicle");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Hatchback", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.ToTable("HatchBack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcdc50b6-7b46-46b4-b659-f02e865f8bf0"),
                            Identifier = "4429f1dc-1113-4ae2-ab4a-fe0a2f92a450",
                            Manufacturer = "Lamborghini",
                            Model = "Ranchero",
                            StartingBid = 7109m,
                            Year = 2000,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("6d7da468-de46-4f5f-a1f5-70addf4f9c53"),
                            Identifier = "d2b3037f-b060-43f9-95bd-a96ff6fd7c1b",
                            Manufacturer = "Land Rover",
                            Model = "Roadster",
                            StartingBid = 11151m,
                            Year = 2014,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("48112217-933c-4d27-ad1d-56d7369f96c7"),
                            Identifier = "015212a3-5ca9-4983-b624-37597c1bf13a",
                            Manufacturer = "Chevrolet",
                            Model = "Altima",
                            StartingBid = 7603m,
                            Year = 1997,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("340d7218-aec1-4040-b78b-34c61804f2f4"),
                            Identifier = "6d6271ad-40b9-4951-9712-b4a69f85d0eb",
                            Manufacturer = "Volvo",
                            Model = "Countach",
                            StartingBid = 20556m,
                            Year = 2009,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("278a03fb-6e7d-4806-a75d-4270147d31e2"),
                            Identifier = "15f4aa9c-4c24-43ba-a60f-b2d2d85f675d",
                            Manufacturer = "Mini",
                            Model = "XTS",
                            StartingBid = 5782m,
                            Year = 2019,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("fa22da69-5d54-4b39-b3df-61ca1f592e45"),
                            Identifier = "38a27097-3d02-4c60-9178-ee96d435e0f6",
                            Manufacturer = "Fiat",
                            Model = "Silverado",
                            StartingBid = 6986m,
                            Year = 1988,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("ef16e374-4794-4d9b-a2a0-09ce446b8b54"),
                            Identifier = "567df195-ad1f-45ff-ba27-d6a91ce9cec9",
                            Manufacturer = "Maserati",
                            Model = "Model S",
                            StartingBid = 14224m,
                            Year = 1957,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("977145aa-2b9d-4aa0-a902-87c9d3d9e7f7"),
                            Identifier = "3c198e42-1522-4e4b-82a8-e90b58d56a8e",
                            Manufacturer = "Mazda",
                            Model = "Sentra",
                            StartingBid = 4348m,
                            Year = 1962,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("a852a068-4630-4660-a1da-c69e833467dc"),
                            Identifier = "ce4e7aba-3ff9-4b5a-93d7-c378c37893d3",
                            Manufacturer = "Fiat",
                            Model = "A8",
                            StartingBid = 2219m,
                            Year = 1987,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("d2de6c8e-0002-4807-8631-5fb53ddb67da"),
                            Identifier = "08edcf1b-6c53-49e1-b029-ad869f69f893",
                            Manufacturer = "Jaguar",
                            Model = "Golf",
                            StartingBid = 22872m,
                            Year = 1996,
                            NumberOfDoors = 5
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Sedan", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.ToTable("Sedan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ac0182-15ab-4092-b97a-ecf6a47064cd"),
                            Identifier = "49e6fc8b-f535-4ce5-89a2-c5d34f692b9a",
                            Manufacturer = "Bentley",
                            Model = "Altima",
                            StartingBid = 24685m,
                            Year = 1955,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("b48fbeb8-d435-4846-8fcd-28cd9af12db3"),
                            Identifier = "63adc9ae-eb8d-43e0-80d0-ef1775fe4112",
                            Manufacturer = "Nissan",
                            Model = "Expedition",
                            StartingBid = 21704m,
                            Year = 2006,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("c0dc4bf6-014f-4fef-8067-d7c2f3c45079"),
                            Identifier = "2f67f0d4-2442-486d-9573-82c0d452752f",
                            Manufacturer = "Mazda",
                            Model = "Aventador",
                            StartingBid = 20473m,
                            Year = 1960,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("97c5938f-61d8-41b4-971d-5fafa907e89d"),
                            Identifier = "31b0cd3a-bd31-4ba6-aebf-96a1793cd057",
                            Manufacturer = "Maserati",
                            Model = "Malibu",
                            StartingBid = 19488m,
                            Year = 2018,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("d2c820bb-abbd-4f10-83c4-41eb8ab4e29a"),
                            Identifier = "0b002f69-bb27-4f48-9fe6-3916703e597d",
                            Manufacturer = "Mercedes Benz",
                            Model = "A4",
                            StartingBid = 24294m,
                            Year = 1965,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("ee5e89dd-4ab1-4ee7-9f03-7398a8b61479"),
                            Identifier = "f8d3bfcf-f376-44ea-86c8-46d929b002fe",
                            Manufacturer = "Tesla",
                            Model = "Civic",
                            StartingBid = 9882m,
                            Year = 1958,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("d15d51dd-0f5b-4a6c-8391-a908647bd62e"),
                            Identifier = "9c320f5c-5961-4932-a178-95994fef0c85",
                            Manufacturer = "Dodge",
                            Model = "Cruze",
                            StartingBid = 14007m,
                            Year = 1996,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("44a8d54f-52a5-4623-b20a-a2a4496bdd0c"),
                            Identifier = "51852392-4513-4a25-a08b-12662fdc6762",
                            Manufacturer = "Polestar",
                            Model = "Spyder",
                            StartingBid = 21112m,
                            Year = 1950,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("0c39ba4f-b3b3-4f89-b11d-026e19b7d02f"),
                            Identifier = "7a2a4257-8de5-46a7-8aaf-786e120a46e7",
                            Manufacturer = "Smart",
                            Model = "Corvette",
                            StartingBid = 20434m,
                            Year = 1999,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("3f7bb23a-58cf-4285-8a94-8dac0f6ca8d3"),
                            Identifier = "2520d40c-5d94-45df-82e2-3c89717208c3",
                            Manufacturer = "Volvo",
                            Model = "Civic",
                            StartingBid = 23465m,
                            Year = 1982,
                            NumberOfDoors = 5
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Suv", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.ToTable("Suv");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0db6a0d-6476-4294-bd1a-9ff180eba012"),
                            Identifier = "9dd44840-daa2-4771-84ce-328e278f9e13",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            StartingBid = 23336m,
                            Year = 1999,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("5f189beb-2bb2-4a65-91ee-5c3d0961d4ac"),
                            Identifier = "74e7b48e-95c9-4c21-bfdd-8bc8336fc843",
                            Manufacturer = "Aston Martin",
                            Model = "Grand Cherokee",
                            StartingBid = 10870m,
                            Year = 1991,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("59d89a8a-5a6a-4969-b1dd-bd6c5e6f4b16"),
                            Identifier = "63ccec42-6dc2-401b-b011-c658a1bc3dc5",
                            Manufacturer = "Chevrolet",
                            Model = "Jetta",
                            StartingBid = 8041m,
                            Year = 2016,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("10bbdcf5-7d2a-4af6-8149-80ed4f965e0f"),
                            Identifier = "bd11b83b-880a-4f17-a2a6-90cc9665a531",
                            Manufacturer = "Land Rover",
                            Model = "1",
                            StartingBid = 3146m,
                            Year = 2000,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("43c0b8eb-b9ac-4b49-adb4-91d379ab593b"),
                            Identifier = "25ee1d62-fce9-4869-b7f3-8211274b5406",
                            Manufacturer = "Bugatti",
                            Model = "Element",
                            StartingBid = 18079m,
                            Year = 1963,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("fe9a49de-9442-4c57-b3c2-28665b05c975"),
                            Identifier = "b4c88a38-2fdc-4786-9d5a-23afd4c55d6e",
                            Manufacturer = "BMW",
                            Model = "Mercielago",
                            StartingBid = 4658m,
                            Year = 2020,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("bcea2705-63bb-402c-8443-119a9d2a2c27"),
                            Identifier = "13433b57-0a13-4ff9-a0d7-3e6c79244a1b",
                            Manufacturer = "Volvo",
                            Model = "ATS",
                            StartingBid = 16724m,
                            Year = 1974,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("bf6e74d7-a7c4-4181-84de-0aa90c19f0f8"),
                            Identifier = "d83e9d02-3b01-4c62-b1da-6fe8f19fc47f",
                            Manufacturer = "Fiat",
                            Model = "XC90",
                            StartingBid = 16723m,
                            Year = 1974,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("e4242445-271f-41c9-866b-a06cc9d350e3"),
                            Identifier = "06084231-62ec-4324-b594-06450705137f",
                            Manufacturer = "Polestar",
                            Model = "Camaro",
                            StartingBid = 7738m,
                            Year = 1995,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("c38df5ac-acb0-4cd9-80f9-249464287d4a"),
                            Identifier = "6f52f2ce-be6d-4dc7-a826-0a5b06ce1cb0",
                            Manufacturer = "Smart",
                            Model = "Explorer",
                            StartingBid = 16312m,
                            Year = 1984,
                            NumberOfSeats = 5
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("LoadCapacity")
                        .HasColumnType("int");

                    b.ToTable("Truck");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b904807-bd0d-4126-84a7-99d1d8e60cbc"),
                            Identifier = "ce9bf647-29b2-4dab-8880-ab45b5458b56",
                            Manufacturer = "Smart",
                            Model = "Model 3",
                            StartingBid = 19944m,
                            Year = 2019,
                            LoadCapacity = 27772
                        },
                        new
                        {
                            Id = new Guid("d58f7970-dff5-405d-96e0-9fedc75f6ddc"),
                            Identifier = "542d3a18-2192-4fe5-8991-f872b8ccc07f",
                            Manufacturer = "Jaguar",
                            Model = "Prius",
                            StartingBid = 15109m,
                            Year = 1967,
                            LoadCapacity = 12264
                        },
                        new
                        {
                            Id = new Guid("b0820feb-e231-454b-acc8-9737f5b44f65"),
                            Identifier = "4140f652-14cb-4dbe-9ab2-529deb730bab",
                            Manufacturer = "Kia",
                            Model = "A8",
                            StartingBid = 6367m,
                            Year = 1985,
                            LoadCapacity = 31299
                        },
                        new
                        {
                            Id = new Guid("061a854f-4901-4481-84e5-7607beb5017d"),
                            Identifier = "c4670c19-8e3c-4639-860a-c0000b8f1de3",
                            Manufacturer = "Polestar",
                            Model = "Camry",
                            StartingBid = 15754m,
                            Year = 1978,
                            LoadCapacity = 10889
                        },
                        new
                        {
                            Id = new Guid("d80e515d-3f39-4783-8894-3909e603dc64"),
                            Identifier = "ff63517f-c3c5-4d56-9922-338256ea6f52",
                            Manufacturer = "Bugatti",
                            Model = "A4",
                            StartingBid = 20108m,
                            Year = 2015,
                            LoadCapacity = 10925
                        },
                        new
                        {
                            Id = new Guid("ad786f35-2969-4837-8757-7466a699ab68"),
                            Identifier = "088cd0de-f351-4340-9d73-3684ed5c2b81",
                            Manufacturer = "Cadillac",
                            Model = "Charger",
                            StartingBid = 7320m,
                            Year = 1970,
                            LoadCapacity = 23021
                        },
                        new
                        {
                            Id = new Guid("985094bf-4684-4907-8877-dfd91e3f60b1"),
                            Identifier = "f2798f41-9595-48c8-abfd-471a39edf710",
                            Manufacturer = "Polestar",
                            Model = "Escalade",
                            StartingBid = 5930m,
                            Year = 2012,
                            LoadCapacity = 23456
                        },
                        new
                        {
                            Id = new Guid("ef3424eb-87ef-44bb-8e10-d55849794d95"),
                            Identifier = "3ee10255-1ee5-4eec-8322-5b594236e361",
                            Manufacturer = "Audi",
                            Model = "Durango",
                            StartingBid = 20194m,
                            Year = 2014,
                            LoadCapacity = 16292
                        },
                        new
                        {
                            Id = new Guid("dc227f9f-1b8b-4184-a544-8c1b52b66c38"),
                            Identifier = "25cfe4b9-bc75-4409-b36d-1783a9fb0ca9",
                            Manufacturer = "Land Rover",
                            Model = "Charger",
                            StartingBid = 16552m,
                            Year = 1964,
                            LoadCapacity = 32911
                        },
                        new
                        {
                            Id = new Guid("c85ff316-8371-4f94-b12f-ee06646a37ea"),
                            Identifier = "224fbf99-1582-4b6c-9a0b-60393f679395",
                            Manufacturer = "Audi",
                            Model = "Impala",
                            StartingBid = 18176m,
                            Year = 1968,
                            LoadCapacity = 23320
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Hatchback", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Hatchback", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Sedan", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Sedan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Suv", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Suv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Truck", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Truck", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
