// <auto-generated />
using System;
using CarAuction.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAuction.Infrastructure.Migrations
{
    [DbContext(typeof(CarAuctionContext))]
    [Migration("20240804155706_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Auction");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartingBid")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.ToTable("Vehicle");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Hatchback", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.ToTable("HatchBack");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e95018a-3f30-4829-9074-8f184cc18c13"),
                            Identifier = "aa543403-9fbd-4f6b-8a59-77686506d1c4",
                            Manufacturer = "Volkswagen",
                            StartingBid = 24787m,
                            Year = 2003,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("2f7036db-bc1c-4dde-b3d4-712643493294"),
                            Identifier = "7a6280f2-b5b3-4965-9449-b660f6b772cc",
                            Manufacturer = "Jeep",
                            StartingBid = 23447m,
                            Year = 1978,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("463e0592-f580-4739-91e5-b650cd227bd2"),
                            Identifier = "6af27c93-549c-4920-b0c8-79c47f296162",
                            Manufacturer = "Tesla",
                            StartingBid = 22236m,
                            Year = 1986,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("b7075f0e-2fcb-491b-8991-d621ef31587c"),
                            Identifier = "e778ec31-a7fa-45cf-9faf-af52d3f9fdc8",
                            Manufacturer = "Ferrari",
                            StartingBid = 21742m,
                            Year = 2005,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("3f424a35-609f-4cd4-8760-4a8e1945ff36"),
                            Identifier = "d16ce965-9b40-4914-b53a-8e7e72fed813",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 17036m,
                            Year = 1958,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("0baaa524-da79-434d-ba2d-66b337926401"),
                            Identifier = "0fdec874-d51f-439a-a26a-a5657ee99109",
                            Manufacturer = "Mazda",
                            StartingBid = 6717m,
                            Year = 1988,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("ace73092-fc93-4328-b906-78b8190d87f3"),
                            Identifier = "db77f24a-e7a3-4812-82c9-8f2db7959b5e",
                            Manufacturer = "Bentley",
                            StartingBid = 11510m,
                            Year = 1971,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("a33efc7f-70c8-417c-bc2e-5cfa017783b2"),
                            Identifier = "a1e2ae17-de93-4e1e-bde4-cebbe982b7dd",
                            Manufacturer = "Volvo",
                            StartingBid = 7576m,
                            Year = 2016,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("0bd54979-24bf-4075-bb13-2f1152cd9319"),
                            Identifier = "399ce515-746d-4d9e-b26f-731f16751900",
                            Manufacturer = "Maserati",
                            StartingBid = 2268m,
                            Year = 2006,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("2a9a73f5-c374-4635-a887-a9b24eb2cd63"),
                            Identifier = "77ff9df5-ac95-4c64-8d55-ebdc22c63cf4",
                            Manufacturer = "Maserati",
                            StartingBid = 5116m,
                            Year = 2006,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("9566e25f-97e0-4053-b56b-122d62a61349"),
                            Identifier = "a38e5944-2890-48e0-9bdf-0e11309f84b2",
                            Manufacturer = "Polestar",
                            StartingBid = 6343m,
                            Year = 1978,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("21eee76f-8e0d-42f8-9538-21e1ed90a81a"),
                            Identifier = "1121562e-79f2-49be-95c9-9403dfbb2e7d",
                            Manufacturer = "Volvo",
                            StartingBid = 14585m,
                            Year = 1958,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("6fa4c435-78eb-4f3e-a075-06cab98c3198"),
                            Identifier = "b509bd10-f5da-4799-b87e-9c73bfba0a42",
                            Manufacturer = "Volkswagen",
                            StartingBid = 6573m,
                            Year = 1992,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("dd433925-7b04-4a0b-884f-749b771c3a3e"),
                            Identifier = "6993e280-38cb-4fe5-b250-d72f0f0f828c",
                            Manufacturer = "Cadillac",
                            StartingBid = 16398m,
                            Year = 2017,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("7d98a384-d64c-47c6-a551-d661f722b591"),
                            Identifier = "3048fdb2-1cac-4f49-8597-632ee264ce9d",
                            Manufacturer = "Polestar",
                            StartingBid = 16034m,
                            Year = 1977,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("760d1151-e738-481b-b987-f3f5f6b5f49a"),
                            Identifier = "6e4666e4-4faf-4a09-bd79-9192dabe9da3",
                            Manufacturer = "Ford",
                            StartingBid = 8979m,
                            Year = 1959,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("d80c6435-7eb6-4aa7-bbf5-34f90faf0d0f"),
                            Identifier = "0a7d5dcb-4440-4e21-832a-1f1cbb90c5f7",
                            Manufacturer = "Ford",
                            StartingBid = 21355m,
                            Year = 1952,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("88f923cc-9b3c-4db1-ba7c-680e38ce2744"),
                            Identifier = "835f4ecf-9719-4e1a-9424-6ffc4b26e62d",
                            Manufacturer = "Cadillac",
                            StartingBid = 4199m,
                            Year = 1986,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("56909362-e636-4704-bfbc-3d09623217d1"),
                            Identifier = "55e4add2-d6a2-4e2a-b15f-3de579f52dd1",
                            Manufacturer = "Chrysler",
                            StartingBid = 12584m,
                            Year = 2011,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("609aa663-f3fc-4108-abd2-ccacd4299b83"),
                            Identifier = "c00af2df-38fd-4498-a95c-717e6537fbd3",
                            Manufacturer = "Hyundai",
                            StartingBid = 13933m,
                            Year = 2012,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("e3ff59f1-ef9a-4b40-93f8-965b00f34f1c"),
                            Identifier = "61e956b7-af15-402f-98d7-e3825581e981",
                            Manufacturer = "Volkswagen",
                            StartingBid = 14195m,
                            Year = 2005,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("69c0f0a0-f7b6-41f9-9fbe-9ab37661db54"),
                            Identifier = "87204995-c006-4d7f-8ca4-08c814495793",
                            Manufacturer = "Cadillac",
                            StartingBid = 2089m,
                            Year = 1990,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("f5aa55a4-fa22-4441-a4dc-7bacc48c2682"),
                            Identifier = "f5a84b8f-5307-45b9-a000-cdac56b3ba31",
                            Manufacturer = "Chevrolet",
                            StartingBid = 14927m,
                            Year = 1978,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("600a9828-d202-4368-b38a-4819849bc42a"),
                            Identifier = "0ab05b1f-a655-4e17-8d4c-e8b3a53ae2b3",
                            Manufacturer = "Toyota",
                            StartingBid = 11841m,
                            Year = 1999,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("f8ae6ac4-b7e2-4b54-95ba-cd2630360bda"),
                            Identifier = "63cbec96-8795-4b45-b8bf-97b595362d20",
                            Manufacturer = "Kia",
                            StartingBid = 19522m,
                            Year = 1991,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("17536aeb-1bc1-4e7b-8b56-a357e8e49d43"),
                            Identifier = "7617c830-ccdf-402e-9abd-2e431a1eb31a",
                            Manufacturer = "Maserati",
                            StartingBid = 17960m,
                            Year = 1991,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("cc290d7f-a4f7-4c72-aeff-daac5cf0de97"),
                            Identifier = "0ba65b1d-cadd-43cb-9647-2b6c587e31e0",
                            Manufacturer = "Porsche",
                            StartingBid = 8427m,
                            Year = 1975,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("1ca7119b-7d8d-4cf2-ab57-77c062e33403"),
                            Identifier = "ad5cd7a5-a941-47c4-94cd-452b38ae1bc9",
                            Manufacturer = "Volvo",
                            StartingBid = 14625m,
                            Year = 1989,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("5d416e3a-e79e-44e4-9c18-4739226a07c3"),
                            Identifier = "2e20d111-7c6b-4fb4-b5b8-eb53dd8f05ea",
                            Manufacturer = "Jeep",
                            StartingBid = 4207m,
                            Year = 2018,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("32135ae4-ee23-4ec6-a8df-457ad50303be"),
                            Identifier = "5d58f1d3-cd35-438a-865b-ab84a387f7fc",
                            Manufacturer = "Bugatti",
                            StartingBid = 8473m,
                            Year = 1975,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("b827281b-2a1d-4b2e-b280-6450a413db5d"),
                            Identifier = "fd78b712-8baf-4a1d-a5c1-df441727a189",
                            Manufacturer = "Aston Martin",
                            StartingBid = 6230m,
                            Year = 1993,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("ef58a7eb-1968-46b1-8875-71f4e2f9a269"),
                            Identifier = "b6fb555a-22a0-4a5a-9ef3-66d2e2b70a4d",
                            Manufacturer = "Cadillac",
                            StartingBid = 7309m,
                            Year = 2012,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("e6c868e6-24cb-44ab-a45a-2c05e4a6efc7"),
                            Identifier = "6d5e38c1-da25-41a5-9a87-65742021faf5",
                            Manufacturer = "Fiat",
                            StartingBid = 20842m,
                            Year = 1956,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("e51aedc3-8bd5-452d-a9cc-bed68c8432bc"),
                            Identifier = "a44c324a-0abc-4666-aef3-4097453531e0",
                            Manufacturer = "Nissan",
                            StartingBid = 12550m,
                            Year = 1970,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("b0006fde-0963-4c28-bfa0-8ae63bcc9ec3"),
                            Identifier = "57374af5-0873-4d92-bd46-91430daa101c",
                            Manufacturer = "Nissan",
                            StartingBid = 15296m,
                            Year = 1970,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("980ab233-d90a-4d17-af05-12ea73c21a4c"),
                            Identifier = "c3bc9c30-079c-42a0-ba74-9b836b30e6fa",
                            Manufacturer = "Chevrolet",
                            StartingBid = 2987m,
                            Year = 1956,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("05e166c7-583e-4d63-8f80-c65f66cbf775"),
                            Identifier = "be617e67-d77c-4c32-9f3a-def70f22d3bb",
                            Manufacturer = "Nissan",
                            StartingBid = 6755m,
                            Year = 1990,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("e77e91a0-d7f0-4369-9a0e-9fcd6c263a1f"),
                            Identifier = "54118081-4baa-4a5a-9841-56e4cf8b0ace",
                            Manufacturer = "Honda",
                            StartingBid = 23930m,
                            Year = 1992,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("f5a8722d-e985-424a-9a7f-0a69228e58ba"),
                            Identifier = "3e4dcbf4-d9b5-4dbf-9909-c04bdb9672c4",
                            Manufacturer = "Jaguar",
                            StartingBid = 1377m,
                            Year = 2005,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("b75bb224-659d-4646-a111-2eaf6c63c64a"),
                            Identifier = "90f3847a-f08c-412a-9d28-723583a6ac14",
                            Manufacturer = "Mini",
                            StartingBid = 17004m,
                            Year = 2019,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("c2a79f02-16a1-49b1-8242-cf1757e19def"),
                            Identifier = "3815e008-5f84-4b21-8363-ff2c48ae2e7a",
                            Manufacturer = "BMW",
                            StartingBid = 23878m,
                            Year = 2010,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("4a460912-aba7-4066-8ec6-054f3255778c"),
                            Identifier = "f5e4d92f-02fe-4846-b75d-1155e6404546",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 2792m,
                            Year = 2002,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("cd84c63b-5475-4545-8fba-8777a06e67c3"),
                            Identifier = "d35b6e6a-bd03-400b-94a2-fade4ccec7a3",
                            Manufacturer = "Chrysler",
                            StartingBid = 13835m,
                            Year = 1958,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("3a133a3a-e05b-47d0-ab37-9bf703dae72d"),
                            Identifier = "ae64fcc7-37fd-4761-b6b1-7b502aeb5bf2",
                            Manufacturer = "Toyota",
                            StartingBid = 10063m,
                            Year = 1997,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("3e621da4-0b81-4072-ba5b-734dd95686f1"),
                            Identifier = "4e8c292a-d396-43cf-9948-1ae9878f8213",
                            Manufacturer = "Lamborghini",
                            StartingBid = 8512m,
                            Year = 1966,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("ffb9cce9-3e88-4f3a-9803-6ec73c24fd20"),
                            Identifier = "0fac0cad-6200-4bea-a0ae-acc36d993b0b",
                            Manufacturer = "BMW",
                            StartingBid = 18594m,
                            Year = 1992,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("1e5debd4-b592-4380-b5d4-47c200a91e36"),
                            Identifier = "ab62eaf8-6484-453b-a2fa-a41c4a7e1527",
                            Manufacturer = "Hyundai",
                            StartingBid = 16516m,
                            Year = 2016,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("1a16c35c-3277-4e83-b0ad-f776947d0a35"),
                            Identifier = "9947614a-bc6d-4dac-ad4a-6213cd53ec97",
                            Manufacturer = "Land Rover",
                            StartingBid = 2590m,
                            Year = 2024,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("bc16dd94-c681-4593-9afb-398bca35c14f"),
                            Identifier = "22b8342b-0a64-4220-abb7-84d0e2772c56",
                            Manufacturer = "Jeep",
                            StartingBid = 24939m,
                            Year = 2000,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("30ac5435-a5c4-4b97-afcd-bf0407cf60a8"),
                            Identifier = "6d93acfd-10d2-469c-a067-763b7585c570",
                            Manufacturer = "Smart",
                            StartingBid = 11087m,
                            Year = 1994,
                            NumberOfDoors = 5
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Sedan", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfDoors")
                        .HasColumnType("int");

                    b.ToTable("Sedan");

                    b.HasData(
                        new
                        {
                            Id = new Guid("774c821b-44ea-4ebc-927c-7093f2fd32aa"),
                            Identifier = "582218dd-8782-4aa8-b18a-c959914dea1b",
                            Manufacturer = "Maserati",
                            StartingBid = 1525m,
                            Year = 1962,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("044f1e5a-037e-4f68-bcdf-069daae12594"),
                            Identifier = "c266654d-f907-4eab-8c05-1630d45315e8",
                            Manufacturer = "Kia",
                            StartingBid = 1695m,
                            Year = 1951,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("0edd857a-2f94-4e8f-8f48-bc2f851b5f51"),
                            Identifier = "6310d27b-09a5-4253-8e0b-3050e47692c2",
                            Manufacturer = "Audi",
                            StartingBid = 16560m,
                            Year = 1983,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("6ef952c2-c3c0-4180-8167-aedb4d026e9f"),
                            Identifier = "91cabb76-2295-43c2-9563-a4296ae9c8d0",
                            Manufacturer = "Porsche",
                            StartingBid = 15497m,
                            Year = 2020,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("677b0dd8-4c71-4c5f-8c85-22113ead3286"),
                            Identifier = "e804ef1c-82a7-4140-b7ca-4526fa1ed623",
                            Manufacturer = "Hyundai",
                            StartingBid = 13614m,
                            Year = 1956,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("e1c9a9ab-91e6-4571-baf8-2581b6f53b60"),
                            Identifier = "c87189ca-ba7c-4f2c-add1-4152f871d2c5",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 8913m,
                            Year = 2024,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("0738449b-28e6-4d74-bc27-2cb2744c5a87"),
                            Identifier = "b9ef7ed7-6383-4422-9b24-5c4afe884cb6",
                            Manufacturer = "BMW",
                            StartingBid = 5149m,
                            Year = 2012,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("d2a53d97-ee10-47f6-90bb-0010e93f5a7b"),
                            Identifier = "2fc6f4bb-acf8-4299-a477-28f8fcf2d07b",
                            Manufacturer = "Land Rover",
                            StartingBid = 7192m,
                            Year = 1972,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("1365d434-3509-4072-80b0-0a31bd80e6c2"),
                            Identifier = "3de2de03-bc1d-4c72-9d84-9e6260fac5a6",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 16419m,
                            Year = 2023,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("045e152a-1ee3-459b-a2eb-f2513b89af2d"),
                            Identifier = "6e0f7128-f4b7-4375-b736-7caaa57ef1af",
                            Manufacturer = "Mini",
                            StartingBid = 4206m,
                            Year = 1950,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("ad596250-ccd9-4469-a07a-d04fa6279791"),
                            Identifier = "415de7f1-a58e-48ae-90e8-a8d067f85f2e",
                            Manufacturer = "Mini",
                            StartingBid = 4119m,
                            Year = 1989,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("96874aaa-1cf2-4895-b75f-e1f7be3977dc"),
                            Identifier = "219e4581-5073-40bc-9cb8-ba053f10e036",
                            Manufacturer = "Hyundai",
                            StartingBid = 12598m,
                            Year = 2021,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("a4eba18b-35a8-4cd8-80b1-e90b00616ca3"),
                            Identifier = "9076f908-b697-4355-8eb3-02ce8f434379",
                            Manufacturer = "Dodge",
                            StartingBid = 3231m,
                            Year = 1980,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("c1fe2c94-0abf-49c6-a676-78c64720ed1e"),
                            Identifier = "0a83aa7c-0eb8-471c-be37-0cb0cf212a1b",
                            Manufacturer = "Bentley",
                            StartingBid = 15086m,
                            Year = 1999,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("4cc60a88-e811-4721-9029-32ee6bd530f6"),
                            Identifier = "e0f818b1-4b42-4981-b0e2-6c97f67ea788",
                            Manufacturer = "Audi",
                            StartingBid = 18563m,
                            Year = 2006,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("28c76101-741b-4c0b-9a9e-4f50bb4538aa"),
                            Identifier = "3ba9a07b-b441-4900-ab88-5250d3adf734",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 14356m,
                            Year = 1958,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("abd981f7-a216-41d5-be39-177dfc22691e"),
                            Identifier = "0298c01a-03d0-4ee8-a332-aadc1861ddab",
                            Manufacturer = "Porsche",
                            StartingBid = 12242m,
                            Year = 2016,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("ab19489f-8d31-402f-a7e2-9b0fff89ea4f"),
                            Identifier = "200ee6d6-20ea-4588-a54d-1897dfc7096c",
                            Manufacturer = "Hyundai",
                            StartingBid = 14336m,
                            Year = 1958,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("ca0d6a40-40da-40e1-b1ac-7597f76ccbe8"),
                            Identifier = "4d5cbee4-0474-4d38-9764-24fc6974e902",
                            Manufacturer = "Mini",
                            StartingBid = 1232m,
                            Year = 2003,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("788d9b91-8d39-4bc9-ba79-970e1a73af3e"),
                            Identifier = "13b9b523-297a-4a9b-9227-1d6c24672c6c",
                            Manufacturer = "Toyota",
                            StartingBid = 2971m,
                            Year = 1973,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("c4fd59f6-9907-4e90-a575-f54c37019b19"),
                            Identifier = "95232301-1d33-4340-8322-eeb495c83fb6",
                            Manufacturer = "Jaguar",
                            StartingBid = 14545m,
                            Year = 1968,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("6bfeafa5-f8bc-4a49-aba8-f56243d2cd47"),
                            Identifier = "5b9342d6-cdd3-4fe9-9f6c-7774294772e3",
                            Manufacturer = "Mini",
                            StartingBid = 18731m,
                            Year = 1953,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("0313a818-eac2-497b-b7bd-83c9881c1fa7"),
                            Identifier = "cb1fa826-e446-4313-9585-b64690ed7ecf",
                            Manufacturer = "Aston Martin",
                            StartingBid = 22833m,
                            Year = 1955,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("2d9cefe6-3cf2-477d-bba5-70c1f7d903d6"),
                            Identifier = "bfc54a0d-6d4a-4755-9370-50358c31e66a",
                            Manufacturer = "Polestar",
                            StartingBid = 15320m,
                            Year = 2004,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("9da0a344-7c6c-48ff-8620-f6b191f71822"),
                            Identifier = "ea40fd3e-4fe1-4ff0-98f5-e391dc8995b2",
                            Manufacturer = "Aston Martin",
                            StartingBid = 12303m,
                            Year = 1981,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("137a4a7a-c6b5-47c0-9e9b-a4e289df5c62"),
                            Identifier = "f8dc9bd2-8eb5-46ce-be2b-0b4497544284",
                            Manufacturer = "Jeep",
                            StartingBid = 1775m,
                            Year = 2005,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("ee01dca5-9b55-4505-a263-d3fdc19c7892"),
                            Identifier = "8bc776cd-2655-4b18-886c-90b256a8ba62",
                            Manufacturer = "Tesla",
                            StartingBid = 7187m,
                            Year = 1997,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("c4883485-fcfa-4255-8984-bc9510dc7133"),
                            Identifier = "aa423734-07e5-47d5-8bf0-844f59e8dcbc",
                            Manufacturer = "Kia",
                            StartingBid = 18003m,
                            Year = 1964,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("cd6f85dd-888e-440f-bbb9-293c4642ad42"),
                            Identifier = "19d9cd64-7935-4523-8ab8-11e946841fd8",
                            Manufacturer = "Lamborghini",
                            StartingBid = 20283m,
                            Year = 1963,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("19046a1f-99ac-4225-928b-7680a96c5eb9"),
                            Identifier = "7e66e591-6bc2-483e-bb1a-f53cb8fc01c1",
                            Manufacturer = "Bugatti",
                            StartingBid = 5257m,
                            Year = 1976,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("b5b23b9f-8666-446d-9b87-b3432fbfff50"),
                            Identifier = "4abc1ec7-0bfd-4581-910e-01c42f5ddf04",
                            Manufacturer = "Chevrolet",
                            StartingBid = 3649m,
                            Year = 1959,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("371c02d8-8f34-43ee-b0c5-3052ae70b583"),
                            Identifier = "fc176b67-dc81-4e7e-be68-f72b08a64cf0",
                            Manufacturer = "BMW",
                            StartingBid = 11001m,
                            Year = 2016,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("4638d67d-a597-420c-89d1-e02b899967dd"),
                            Identifier = "e1011981-7e52-4528-881b-c26c908e04bc",
                            Manufacturer = "Smart",
                            StartingBid = 3405m,
                            Year = 1953,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("b9e558b0-ab82-42b7-9545-699ccba32a2b"),
                            Identifier = "f4f1918b-9058-4a23-8496-16244450ae43",
                            Manufacturer = "Fiat",
                            StartingBid = 20145m,
                            Year = 1962,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("f400de0c-686f-4e8a-9c8c-a21e91e976da"),
                            Identifier = "3172cbd6-50e3-48b3-81e3-8e7f3935eaae",
                            Manufacturer = "Aston Martin",
                            StartingBid = 5215m,
                            Year = 2003,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("eedd5bd7-63f2-41ca-8f62-6ad519acf1be"),
                            Identifier = "7c8e4d54-5ed4-46eb-b890-21bfd580e2a5",
                            Manufacturer = "Fiat",
                            StartingBid = 13539m,
                            Year = 1973,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("76e79ee0-0c8e-4e1b-b5c2-366500aec831"),
                            Identifier = "5502c292-74bd-4003-84ad-4e157f23767f",
                            Manufacturer = "Bentley",
                            StartingBid = 17765m,
                            Year = 2009,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("d021089c-6b4a-44d4-b34a-9bf90c0119a1"),
                            Identifier = "6374a3ab-8230-4a1f-b10f-599a444b8604",
                            Manufacturer = "Aston Martin",
                            StartingBid = 20025m,
                            Year = 1977,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("d49110db-81ca-4b36-b419-6020d61ac5fa"),
                            Identifier = "48616902-b1a6-4963-96d7-a8cbde51b46e",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 11023m,
                            Year = 1983,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("0a2b3679-8764-46b2-85ac-31f2a7efa862"),
                            Identifier = "53da6e84-7c0f-4e4b-be7a-8f64095f32e1",
                            Manufacturer = "Porsche",
                            StartingBid = 14945m,
                            Year = 1971,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("339f7753-ff75-4fb5-a095-7514ef872ebd"),
                            Identifier = "7d86944e-9e20-4845-95ff-d6c1c13a9eaf",
                            Manufacturer = "Mazda",
                            StartingBid = 4319m,
                            Year = 1992,
                            NumberOfDoors = 5
                        },
                        new
                        {
                            Id = new Guid("7a29fb2c-a34d-4a50-8d90-a5bf8145b7ab"),
                            Identifier = "93fcf149-d4ff-4a21-b30f-1eb852b8238c",
                            Manufacturer = "Audi",
                            StartingBid = 3044m,
                            Year = 2021,
                            NumberOfDoors = 1
                        },
                        new
                        {
                            Id = new Guid("7296b084-3e87-4853-a473-8f79804ba7a3"),
                            Identifier = "5bbfa9ea-e743-4da9-8587-58e540288b2d",
                            Manufacturer = "Toyota",
                            StartingBid = 18197m,
                            Year = 2019,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("dafb1274-96c4-4a35-9948-cf06537ec619"),
                            Identifier = "e104f213-927c-409b-8a4d-ce0a6e282246",
                            Manufacturer = "Aston Martin",
                            StartingBid = 21274m,
                            Year = 1976,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("c6281cbc-e03f-4473-b450-00c06172c1da"),
                            Identifier = "6b6ff99e-7e6f-4901-8480-2a88db8ce0e1",
                            Manufacturer = "Honda",
                            StartingBid = 21432m,
                            Year = 2019,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("7475bc0c-07c8-4a18-9c45-b90ecf337a71"),
                            Identifier = "424ab7aa-e5b8-4682-9217-29e6451ab11b",
                            Manufacturer = "Fiat",
                            StartingBid = 13659m,
                            Year = 1965,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("6d389a21-b596-49b5-b243-8f851550bb47"),
                            Identifier = "9bdbc496-fbc9-49d8-88b1-a61aa9b5db57",
                            Manufacturer = "Smart",
                            StartingBid = 4180m,
                            Year = 1958,
                            NumberOfDoors = 3
                        },
                        new
                        {
                            Id = new Guid("45999a0e-cb81-4505-b71a-7831b2510ce5"),
                            Identifier = "8a8c58cd-2e45-4abd-bd00-5625cd5924c1",
                            Manufacturer = "Fiat",
                            StartingBid = 6195m,
                            Year = 1985,
                            NumberOfDoors = 2
                        },
                        new
                        {
                            Id = new Guid("f4480985-c83f-42a9-b0d4-70a7ceb8463f"),
                            Identifier = "bc948efa-f7d6-4b18-81ff-0adce5a2ed8d",
                            Manufacturer = "Aston Martin",
                            StartingBid = 23285m,
                            Year = 1964,
                            NumberOfDoors = 4
                        },
                        new
                        {
                            Id = new Guid("5bbe6fba-7299-4d78-8d53-c9cdaa800522"),
                            Identifier = "b2068aa0-f9a8-41dc-bddd-095f43c44cc3",
                            Manufacturer = "Smart",
                            StartingBid = 12822m,
                            Year = 2011,
                            NumberOfDoors = 2
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Suv", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.ToTable("Suv");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d66f16a-df11-4069-a591-4bca9211c702"),
                            Identifier = "9d49f426-81e2-4496-81a5-af0e994bfc24",
                            Manufacturer = "BMW",
                            StartingBid = 13854m,
                            Year = 1953,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("d1013fba-55ab-4fa6-b71c-5a42db608a59"),
                            Identifier = "9354471e-713e-4e66-9fff-dc315d2db559",
                            Manufacturer = "Tesla",
                            StartingBid = 4951m,
                            Year = 1975,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("e1a1efb9-397d-414d-bc0b-d4020912d83d"),
                            Identifier = "a652a803-1ae9-4bfc-82eb-827f58ab51dc",
                            Manufacturer = "Tesla",
                            StartingBid = 7314m,
                            Year = 2006,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("518b9d16-b3e7-4331-ad2a-29aeaa85dbb5"),
                            Identifier = "51420df8-f384-4630-b5f4-ce52ec2a48aa",
                            Manufacturer = "Dodge",
                            StartingBid = 21142m,
                            Year = 1976,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("77a04ed0-7dfb-4751-a4fa-a848d508d532"),
                            Identifier = "7f131147-2dc5-45dc-b8d7-dbae18831450",
                            Manufacturer = "Aston Martin",
                            StartingBid = 3873m,
                            Year = 1972,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("fa3fb964-0f92-4a7e-9c65-1f51559434fa"),
                            Identifier = "e0d260e6-dade-4e64-b938-c965bbcd9b4e",
                            Manufacturer = "Polestar",
                            StartingBid = 20117m,
                            Year = 2014,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("99101f6e-3ece-4007-8b2c-fd7553f1dc7d"),
                            Identifier = "d8778b85-3d01-430d-83ee-fbadc6dc79a8",
                            Manufacturer = "Hyundai",
                            StartingBid = 8476m,
                            Year = 1960,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("288d541a-f698-467a-9039-89066f4135ff"),
                            Identifier = "2c9291af-87a0-424e-99a7-4001e64bd329",
                            Manufacturer = "Audi",
                            StartingBid = 9856m,
                            Year = 1980,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("58ef627b-d19e-415f-8919-ef5b43a7e034"),
                            Identifier = "21975019-f89e-4741-b380-ee2ecf1839a0",
                            Manufacturer = "Ford",
                            StartingBid = 17362m,
                            Year = 1973,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("5cafcd92-65cd-4378-972c-aaa21638e50d"),
                            Identifier = "45eab6bf-af5d-47e0-a951-67601855d1f7",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 18598m,
                            Year = 1997,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("3f1acc07-bbb5-43f8-920d-5868e3efc66c"),
                            Identifier = "b99819ba-4b98-48cf-ae39-6ba71301d925",
                            Manufacturer = "Lamborghini",
                            StartingBid = 24843m,
                            Year = 1990,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("d0b643ec-8e24-4772-81e9-6c8242d2c8d1"),
                            Identifier = "36f9dd61-e8f2-4039-b0e7-8cd17a0ba242",
                            Manufacturer = "Jaguar",
                            StartingBid = 16171m,
                            Year = 1963,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("533aa325-2407-4651-8b9d-f23727379aea"),
                            Identifier = "413f7b2b-0641-49cd-9c7c-97233bb183ce",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 1417m,
                            Year = 2002,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("7545d9f1-bffa-4848-b68e-df260a4d1140"),
                            Identifier = "75980872-acaa-4aab-a6a7-d7d9692a685e",
                            Manufacturer = "Mini",
                            StartingBid = 1931m,
                            Year = 1972,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("9ded0bb6-9288-4b50-ba28-eb259ec50c3b"),
                            Identifier = "38bb0d86-13a4-4b4f-893a-3d256daccf12",
                            Manufacturer = "Land Rover",
                            StartingBid = 13676m,
                            Year = 1988,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("c585bd23-2fca-4534-969d-6a693c7aeaf0"),
                            Identifier = "b4cb929b-31e3-4a35-b860-6dae1771176e",
                            Manufacturer = "Cadillac",
                            StartingBid = 22566m,
                            Year = 1985,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("1f10e3a3-0036-416a-a700-85560126f98d"),
                            Identifier = "5e46b134-3049-439d-a615-f54cbcec288d",
                            Manufacturer = "Kia",
                            StartingBid = 24754m,
                            Year = 1980,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("deafc5e2-8d38-455c-9b02-ac325771413d"),
                            Identifier = "797025a2-24c7-4673-903b-3472a800aab6",
                            Manufacturer = "Audi",
                            StartingBid = 10526m,
                            Year = 1995,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("aa75ac11-a480-4509-847a-e55e37ee372f"),
                            Identifier = "f9867c91-6b5f-40a7-ad82-c56916f53104",
                            Manufacturer = "Tesla",
                            StartingBid = 13757m,
                            Year = 1998,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("851a67aa-b7af-40ed-8663-21a32e4fe56a"),
                            Identifier = "99b2841d-7075-484c-a631-fc8275abc63a",
                            Manufacturer = "Land Rover",
                            StartingBid = 18093m,
                            Year = 1958,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("95e85db5-52b0-4238-b16c-eb818b23b532"),
                            Identifier = "7cae1850-06e7-4516-accb-80e6b69e72fc",
                            Manufacturer = "Jaguar",
                            StartingBid = 7239m,
                            Year = 1955,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("ce9c4eac-d801-4b4f-b6f6-2400da2c960c"),
                            Identifier = "fc92ceec-fc65-435c-b95a-ae6df56ca8ea",
                            Manufacturer = "Aston Martin",
                            StartingBid = 22674m,
                            Year = 1962,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("03948eae-630a-4ec6-9d9c-353314ce2f66"),
                            Identifier = "bbd6d4ad-4637-465a-90f2-6e64dedb91a4",
                            Manufacturer = "Mazda",
                            StartingBid = 6519m,
                            Year = 2010,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("e292d8e8-f712-47c8-8903-537092be5ca7"),
                            Identifier = "aba60d72-2ecd-4338-8f87-63ffec168284",
                            Manufacturer = "Porsche",
                            StartingBid = 24385m,
                            Year = 2009,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("a61d89f0-8329-4641-8cc3-46e314b3902b"),
                            Identifier = "3935d7c8-bffe-4271-86d4-fa4848e2eadb",
                            Manufacturer = "Hyundai",
                            StartingBid = 1502m,
                            Year = 2019,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("770bc526-c109-45df-bba1-521146a9936c"),
                            Identifier = "1f21cdf0-6b8a-4c4e-8e0d-38a4a450895a",
                            Manufacturer = "Jaguar",
                            StartingBid = 8795m,
                            Year = 1964,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("b01ffc0e-c28a-461c-b23d-24b2d5f396ea"),
                            Identifier = "66d3b5cf-cf99-41b4-9da5-6160d31e0fc0",
                            Manufacturer = "Volvo",
                            StartingBid = 2805m,
                            Year = 1984,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("e10423f9-3c42-4cfe-b58d-dc8a4b828a3f"),
                            Identifier = "22dfa04b-d4e9-4e90-9553-089cb67196bc",
                            Manufacturer = "Toyota",
                            StartingBid = 16032m,
                            Year = 1999,
                            NumberOfSeats = 6
                        },
                        new
                        {
                            Id = new Guid("1a090a94-f09c-4a0e-a479-fc36c592ad7a"),
                            Identifier = "72b322f6-50b1-49c0-8079-214cc80baefa",
                            Manufacturer = "Kia",
                            StartingBid = 6617m,
                            Year = 1981,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("b716099b-fd43-422c-8471-8d43b5108715"),
                            Identifier = "6398697e-962c-4218-a6df-b5bdcc8fbaa2",
                            Manufacturer = "Nissan",
                            StartingBid = 13489m,
                            Year = 1950,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("0f8c2fa3-e658-467e-aef9-65258c184378"),
                            Identifier = "791a8804-97f5-4a38-831d-0851f278ea8e",
                            Manufacturer = "Chevrolet",
                            StartingBid = 20961m,
                            Year = 1953,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("197c99d5-e25b-458b-af8d-761e81d7a830"),
                            Identifier = "de2021f1-bce4-4712-a6bc-6b38d06bfb74",
                            Manufacturer = "Volkswagen",
                            StartingBid = 19538m,
                            Year = 2003,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("2ee6efbe-4b43-495c-9276-0240c9a60acc"),
                            Identifier = "d29618d6-d441-4ff1-b00f-a2af95748160",
                            Manufacturer = "Hyundai",
                            StartingBid = 8260m,
                            Year = 1954,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("88db8d45-9ea0-4bf7-bfe2-785d1cf6838e"),
                            Identifier = "2db5a88d-a748-425c-bfae-615ad801bb47",
                            Manufacturer = "Bentley",
                            StartingBid = 22065m,
                            Year = 1956,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("71d78121-9f22-405a-b738-c3116eb93a74"),
                            Identifier = "44f56992-9c62-4131-a1c5-5a00356dae43",
                            Manufacturer = "Aston Martin",
                            StartingBid = 7933m,
                            Year = 1962,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("e1140e74-2aa4-4580-bba0-59020dc60e5c"),
                            Identifier = "43191fcf-c325-4b82-bd65-0db85b122706",
                            Manufacturer = "Land Rover",
                            StartingBid = 14435m,
                            Year = 1982,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("41b148c0-466c-4c17-b7cd-655611919d1b"),
                            Identifier = "582b711b-bdbd-42d0-8ce3-388e9e2ec0e0",
                            Manufacturer = "Ferrari",
                            StartingBid = 8173m,
                            Year = 1988,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("0eb0eb30-1b45-484b-a907-2725d8c57d0a"),
                            Identifier = "708250f9-fd9d-47ae-a9ab-59f9212f651a",
                            Manufacturer = "Polestar",
                            StartingBid = 2619m,
                            Year = 1985,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("3cd9d349-82f6-470c-a23e-6e357b4f32ba"),
                            Identifier = "2dfba345-9458-457a-b3fd-a4809cbe2830",
                            Manufacturer = "Toyota",
                            StartingBid = 10976m,
                            Year = 1994,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("921b441c-5d2e-44c8-8207-543190ed65ac"),
                            Identifier = "cf806be0-adc5-44c4-b1b2-be161d6242b6",
                            Manufacturer = "Jeep",
                            StartingBid = 22519m,
                            Year = 1954,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("d437f289-d1b3-4e25-b258-0f55b098f7cb"),
                            Identifier = "f81ee63a-6c1e-45ed-bff7-64ac07c23441",
                            Manufacturer = "Volvo",
                            StartingBid = 2865m,
                            Year = 1980,
                            NumberOfSeats = 7
                        },
                        new
                        {
                            Id = new Guid("a6bb6784-1532-4dff-b012-f39f6b0dad6b"),
                            Identifier = "8159bfd8-dc43-4eaf-8bdd-00a36938f43e",
                            Manufacturer = "Dodge",
                            StartingBid = 20945m,
                            Year = 1962,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("926f15dd-fb11-4396-b1cf-01528670edd2"),
                            Identifier = "9cf414d6-4455-4c11-8ee3-1afea5e60548",
                            Manufacturer = "Hyundai",
                            StartingBid = 20934m,
                            Year = 2022,
                            NumberOfSeats = 9
                        },
                        new
                        {
                            Id = new Guid("4c00e00d-b5c3-465e-b5c0-2a6839ead52b"),
                            Identifier = "af57ade6-9dfd-4595-808a-4e691b2c4bd5",
                            Manufacturer = "Toyota",
                            StartingBid = 22440m,
                            Year = 1966,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("4f3ef718-6373-4643-99e1-2b14a26b5d75"),
                            Identifier = "112d2965-4974-454d-9c8e-bd56a19cd690",
                            Manufacturer = "Audi",
                            StartingBid = 2097m,
                            Year = 2003,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("f6eed512-1161-468c-b52d-19a552852ed8"),
                            Identifier = "5427c4c3-f12f-4641-b46e-c82a7f0619e6",
                            Manufacturer = "Bentley",
                            StartingBid = 12392m,
                            Year = 1981,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("dad57c2c-445a-4ed7-baa4-9da265f631dd"),
                            Identifier = "20df1e24-192a-4ca2-850f-e303a934d6a6",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 10636m,
                            Year = 2020,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("2b0198b6-121b-4c94-903c-2eefc0d733a1"),
                            Identifier = "6f838eea-afe6-4ac9-95c0-add304f6dafb",
                            Manufacturer = "Toyota",
                            StartingBid = 21311m,
                            Year = 2001,
                            NumberOfSeats = 8
                        },
                        new
                        {
                            Id = new Guid("cc75d6ad-c39d-4f20-a8e7-5f1dd94971ef"),
                            Identifier = "847968c6-3c7a-44ea-990e-578ac2e13378",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 24677m,
                            Year = 1978,
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("c02e9689-d460-48a9-b41f-a2556545cfcb"),
                            Identifier = "b0e8ce94-af3c-40ae-afa5-16be2aafb434",
                            Manufacturer = "Ford",
                            StartingBid = 19209m,
                            Year = 1973,
                            NumberOfSeats = 8
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Truck", b =>
                {
                    b.HasBaseType("CarAuction.Domain.Entities.Vehicle");

                    b.Property<int>("LoadCapacity")
                        .HasColumnType("int");

                    b.ToTable("Truck");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3db3695-90e7-4077-aeb9-9b8d5f617d02"),
                            Identifier = "174c1ac8-7e02-485f-ade8-2c44bcd289cb",
                            Manufacturer = "Jeep",
                            StartingBid = 3473m,
                            Year = 1957,
                            LoadCapacity = 34360
                        },
                        new
                        {
                            Id = new Guid("b6b57aa9-1145-46e5-9720-5ae75ddd44a2"),
                            Identifier = "d32fa881-1911-484f-8c13-76e678b71510",
                            Manufacturer = "Volkswagen",
                            StartingBid = 15503m,
                            Year = 1965,
                            LoadCapacity = 14108
                        },
                        new
                        {
                            Id = new Guid("5b78dcfd-710d-42d2-bbce-b9afb705c442"),
                            Identifier = "156a428d-6261-483a-a613-889200f3d969",
                            Manufacturer = "Maserati",
                            StartingBid = 5494m,
                            Year = 1987,
                            LoadCapacity = 11196
                        },
                        new
                        {
                            Id = new Guid("5d51f6c1-3270-4c6d-b63e-70a7694415b1"),
                            Identifier = "7b22499f-d12a-4d17-96f3-acc3eb8de1a9",
                            Manufacturer = "Chevrolet",
                            StartingBid = 4927m,
                            Year = 1974,
                            LoadCapacity = 33047
                        },
                        new
                        {
                            Id = new Guid("0de917f8-7db4-40aa-b7f4-3e56ff3baee9"),
                            Identifier = "0b7d9ffd-48a6-43dd-b990-0fc1410864a8",
                            Manufacturer = "Volvo",
                            StartingBid = 5389m,
                            Year = 1968,
                            LoadCapacity = 24149
                        },
                        new
                        {
                            Id = new Guid("73f6f9e5-7afb-4699-a3e1-45b5fa45922e"),
                            Identifier = "2961d49d-e28e-4486-b2e0-d8d3833ffe2f",
                            Manufacturer = "Kia",
                            StartingBid = 24086m,
                            Year = 1998,
                            LoadCapacity = 11040
                        },
                        new
                        {
                            Id = new Guid("9307bae3-ce44-4853-823a-80ff412a4fc4"),
                            Identifier = "af2804d3-ce9c-4da8-ac7f-e1baf7e2b0a6",
                            Manufacturer = "Jaguar",
                            StartingBid = 7774m,
                            Year = 1957,
                            LoadCapacity = 19477
                        },
                        new
                        {
                            Id = new Guid("dbd3df4c-1b71-47ee-aee2-96e6d57f7602"),
                            Identifier = "1a29c2b4-4200-4de4-923f-1f9c70afe9b4",
                            Manufacturer = "Chevrolet",
                            StartingBid = 11689m,
                            Year = 2017,
                            LoadCapacity = 21113
                        },
                        new
                        {
                            Id = new Guid("eefcfd2f-1078-4684-8922-a55d71e35d62"),
                            Identifier = "995cb171-f183-4ca2-ba61-b3aa4267057c",
                            Manufacturer = "Ford",
                            StartingBid = 18025m,
                            Year = 1954,
                            LoadCapacity = 24409
                        },
                        new
                        {
                            Id = new Guid("f2c607fd-5fbd-45ea-8019-2381c17b22fd"),
                            Identifier = "0120c170-8f57-4740-943f-466a55746823",
                            Manufacturer = "Jeep",
                            StartingBid = 23324m,
                            Year = 2015,
                            LoadCapacity = 10847
                        },
                        new
                        {
                            Id = new Guid("2ed1411d-6900-4707-90db-27fee490b6e3"),
                            Identifier = "58fddc4e-5f7d-4dca-93ae-8ed2e856cc7b",
                            Manufacturer = "Cadillac",
                            StartingBid = 5921m,
                            Year = 1960,
                            LoadCapacity = 24309
                        },
                        new
                        {
                            Id = new Guid("c915ed0e-0358-4a2f-a84e-b21400ffd71b"),
                            Identifier = "970f36a9-a6f0-480f-9847-bae7674ce0ef",
                            Manufacturer = "Tesla",
                            StartingBid = 4694m,
                            Year = 1976,
                            LoadCapacity = 30719
                        },
                        new
                        {
                            Id = new Guid("f063a19a-c255-4ff8-8c92-7b1753be5387"),
                            Identifier = "2df79bfc-919b-477e-b940-e7a52787ef05",
                            Manufacturer = "Ford",
                            StartingBid = 18258m,
                            Year = 1963,
                            LoadCapacity = 24628
                        },
                        new
                        {
                            Id = new Guid("c98d335c-3665-443a-bda1-17cf788eb76e"),
                            Identifier = "021b6053-151a-4597-adb5-cc90b4f53002",
                            Manufacturer = "Polestar",
                            StartingBid = 17946m,
                            Year = 1978,
                            LoadCapacity = 26370
                        },
                        new
                        {
                            Id = new Guid("38ae2ebb-d80f-48e4-81d4-21f20df776ad"),
                            Identifier = "7e6f9bf8-c417-44fb-82ac-a386c1a5483a",
                            Manufacturer = "Volvo",
                            StartingBid = 14980m,
                            Year = 1956,
                            LoadCapacity = 17364
                        },
                        new
                        {
                            Id = new Guid("1f640420-e15c-456a-b24a-8972a38f78db"),
                            Identifier = "f931c46e-70d2-47e6-ac58-726f010edf80",
                            Manufacturer = "Chrysler",
                            StartingBid = 10469m,
                            Year = 1954,
                            LoadCapacity = 19201
                        },
                        new
                        {
                            Id = new Guid("cc528f66-c65c-4fcb-8bda-44ca168dd0dd"),
                            Identifier = "521b2db8-1524-4c79-ba38-569376c54532",
                            Manufacturer = "Tesla",
                            StartingBid = 1994m,
                            Year = 1994,
                            LoadCapacity = 25682
                        },
                        new
                        {
                            Id = new Guid("f40f3593-47de-49c0-a37b-62cdd81ae77f"),
                            Identifier = "91134e43-087f-4613-912e-91dd2a963208",
                            Manufacturer = "Maserati",
                            StartingBid = 18802m,
                            Year = 2010,
                            LoadCapacity = 29986
                        },
                        new
                        {
                            Id = new Guid("19e197ee-bfdd-4054-9cb0-611f05810613"),
                            Identifier = "b87fc9d4-68a3-4938-93fd-32b9ab1fa3a1",
                            Manufacturer = "BMW",
                            StartingBid = 4424m,
                            Year = 1994,
                            LoadCapacity = 10695
                        },
                        new
                        {
                            Id = new Guid("27e7b2fb-5c76-4ee5-a643-971be2127bf7"),
                            Identifier = "a04f7a43-823f-462d-94a3-ac1c68c32e06",
                            Manufacturer = "Fiat",
                            StartingBid = 6774m,
                            Year = 1965,
                            LoadCapacity = 23061
                        },
                        new
                        {
                            Id = new Guid("d14c5914-4e82-421b-a8f0-a174bd14c20e"),
                            Identifier = "00e23394-86fd-4885-94ca-9429f9ae66ec",
                            Manufacturer = "Aston Martin",
                            StartingBid = 13803m,
                            Year = 1957,
                            LoadCapacity = 22924
                        },
                        new
                        {
                            Id = new Guid("c65199a8-b5b2-4452-9f04-be0022d0bab0"),
                            Identifier = "1099cb5a-533f-4c42-842a-526eff1305b8",
                            Manufacturer = "Bugatti",
                            StartingBid = 5424m,
                            Year = 1969,
                            LoadCapacity = 30001
                        },
                        new
                        {
                            Id = new Guid("59c3aaa9-91f2-4684-85f3-d3efb52c73f2"),
                            Identifier = "5abe41eb-f3b7-4ba4-a6ff-2c56b1d0be8d",
                            Manufacturer = "Ferrari",
                            StartingBid = 14789m,
                            Year = 1964,
                            LoadCapacity = 11040
                        },
                        new
                        {
                            Id = new Guid("962f40e7-2c85-45ff-ad3f-867db2c41e3a"),
                            Identifier = "75ae4211-fa45-4a9c-ab15-57276f854b42",
                            Manufacturer = "Toyota",
                            StartingBid = 2653m,
                            Year = 1993,
                            LoadCapacity = 12085
                        },
                        new
                        {
                            Id = new Guid("dfc4f83d-0945-452a-8e31-a96fa4868802"),
                            Identifier = "9b10b1ac-1b0c-4d17-8e26-3eadce8bed13",
                            Manufacturer = "Ford",
                            StartingBid = 2340m,
                            Year = 1986,
                            LoadCapacity = 12916
                        },
                        new
                        {
                            Id = new Guid("8755e6d9-50db-440c-968c-609a34c72d86"),
                            Identifier = "78bf9d06-b0c7-46fc-8599-82a18d8dc0c3",
                            Manufacturer = "Aston Martin",
                            StartingBid = 24636m,
                            Year = 1954,
                            LoadCapacity = 20961
                        },
                        new
                        {
                            Id = new Guid("c4d1ed7c-cfd7-4a29-ac39-d04f27162506"),
                            Identifier = "1265d9f3-9ee3-40a4-add6-b441447aa2d9",
                            Manufacturer = "Jaguar",
                            StartingBid = 7403m,
                            Year = 2006,
                            LoadCapacity = 32884
                        },
                        new
                        {
                            Id = new Guid("545ab8bc-76f0-41f9-a2bc-cf87a4e63b62"),
                            Identifier = "46dbe099-768d-44b7-a3f1-176b5394fc5c",
                            Manufacturer = "Volkswagen",
                            StartingBid = 11486m,
                            Year = 1999,
                            LoadCapacity = 16988
                        },
                        new
                        {
                            Id = new Guid("471218b2-6461-4042-83e6-2944d24f325b"),
                            Identifier = "ffca9482-b124-4596-8c5d-fda08168bb25",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 5282m,
                            Year = 1957,
                            LoadCapacity = 15635
                        },
                        new
                        {
                            Id = new Guid("009daeb8-a2ef-4a5f-a65e-15223dcc9f73"),
                            Identifier = "130bac51-8928-4a0d-b22e-bb092fd1fa50",
                            Manufacturer = "Mercedes Benz",
                            StartingBid = 17819m,
                            Year = 2022,
                            LoadCapacity = 28208
                        },
                        new
                        {
                            Id = new Guid("6f1ea977-104a-43b7-bc10-ec39aea1cd20"),
                            Identifier = "027979e4-288d-420c-9574-e97eef18077e",
                            Manufacturer = "Nissan",
                            StartingBid = 10396m,
                            Year = 1987,
                            LoadCapacity = 19664
                        },
                        new
                        {
                            Id = new Guid("784cd549-04d9-4ac4-b649-62b2085ab72e"),
                            Identifier = "f79a14d4-8739-4ad5-afc0-7e84d130cd16",
                            Manufacturer = "Dodge",
                            StartingBid = 23520m,
                            Year = 1992,
                            LoadCapacity = 32183
                        },
                        new
                        {
                            Id = new Guid("50e125eb-89d3-429a-865e-855c2e87f864"),
                            Identifier = "ae36a777-d70c-4a66-98b9-34a7bbfdae8b",
                            Manufacturer = "Bugatti",
                            StartingBid = 17717m,
                            Year = 1982,
                            LoadCapacity = 13663
                        },
                        new
                        {
                            Id = new Guid("28edf843-143d-49b6-8d8e-1795afd7269f"),
                            Identifier = "1b52a959-7ba8-4374-a48b-96379871ac8f",
                            Manufacturer = "Cadillac",
                            StartingBid = 23457m,
                            Year = 1996,
                            LoadCapacity = 28896
                        },
                        new
                        {
                            Id = new Guid("cf77c942-7e61-449a-b975-172fe30aae6d"),
                            Identifier = "bcd3b6ef-1deb-4070-a7d3-f21551da237d",
                            Manufacturer = "Land Rover",
                            StartingBid = 17892m,
                            Year = 1977,
                            LoadCapacity = 32174
                        },
                        new
                        {
                            Id = new Guid("aa9c9cba-1cb4-41ef-bb47-4edc0d8f74a5"),
                            Identifier = "5f1c4fe4-cfeb-410c-814c-cb7c288f47fa",
                            Manufacturer = "Mazda",
                            StartingBid = 18648m,
                            Year = 1965,
                            LoadCapacity = 33631
                        },
                        new
                        {
                            Id = new Guid("6bb7c97d-2841-484a-910c-32969ef23636"),
                            Identifier = "113a70e5-0763-4da3-99cb-fd5a12fe9fd9",
                            Manufacturer = "Kia",
                            StartingBid = 10127m,
                            Year = 2016,
                            LoadCapacity = 20766
                        },
                        new
                        {
                            Id = new Guid("b5c574c6-4f01-4b80-8b67-5ec5e1794458"),
                            Identifier = "6bdef035-42f2-40aa-95e5-3f0aa1c3f2f2",
                            Manufacturer = "Honda",
                            StartingBid = 17113m,
                            Year = 1975,
                            LoadCapacity = 19455
                        },
                        new
                        {
                            Id = new Guid("44efc62c-68de-4a1f-b7b3-3dbea7df5b7a"),
                            Identifier = "1f14afb9-df0d-49b5-a29e-8f3f7a1acd3f",
                            Manufacturer = "Toyota",
                            StartingBid = 8346m,
                            Year = 2003,
                            LoadCapacity = 31519
                        },
                        new
                        {
                            Id = new Guid("4866ef2f-e1a5-436c-b619-0a436c00051a"),
                            Identifier = "e7156a99-df18-40a8-ae29-27ee6d983ec6",
                            Manufacturer = "Bugatti",
                            StartingBid = 6206m,
                            Year = 1997,
                            LoadCapacity = 33311
                        },
                        new
                        {
                            Id = new Guid("380c021d-596c-406d-a276-d56f6f41ad94"),
                            Identifier = "fb78486b-fde0-4f80-83da-61085b543db3",
                            Manufacturer = "Chrysler",
                            StartingBid = 5946m,
                            Year = 2024,
                            LoadCapacity = 28159
                        },
                        new
                        {
                            Id = new Guid("a502e588-8e5a-474b-8c46-afe7b07e6cfc"),
                            Identifier = "85b0b3db-3c4d-47da-aee5-d90a16140c81",
                            Manufacturer = "Chevrolet",
                            StartingBid = 21574m,
                            Year = 1988,
                            LoadCapacity = 27890
                        },
                        new
                        {
                            Id = new Guid("6b4c2eb8-669b-4c17-aea6-5df72a236a85"),
                            Identifier = "b88e3b2e-c1e3-41b4-ab97-4b40085d8310",
                            Manufacturer = "Kia",
                            StartingBid = 23862m,
                            Year = 2015,
                            LoadCapacity = 22415
                        },
                        new
                        {
                            Id = new Guid("dbd99461-8db0-448a-8062-9d80fa6d1d68"),
                            Identifier = "49b01097-ae0a-488b-8c86-c8f99f1572c8",
                            Manufacturer = "Fiat",
                            StartingBid = 2398m,
                            Year = 2003,
                            LoadCapacity = 32439
                        },
                        new
                        {
                            Id = new Guid("95f5e766-b72d-4e95-8139-607b1c36398e"),
                            Identifier = "7b65a4ce-fd60-4421-9d4b-75bca9cade9c",
                            Manufacturer = "Audi",
                            StartingBid = 1286m,
                            Year = 2016,
                            LoadCapacity = 32828
                        },
                        new
                        {
                            Id = new Guid("f1c34437-ec0f-4c2f-97dd-c531b009fc66"),
                            Identifier = "705be1f0-2bd5-4c9a-83a9-ba42f0c6fc15",
                            Manufacturer = "Rolls Royce",
                            StartingBid = 6636m,
                            Year = 2016,
                            LoadCapacity = 16692
                        },
                        new
                        {
                            Id = new Guid("fccd3a2e-6418-4f9a-a45e-405348ecdcdf"),
                            Identifier = "3957eccd-a7a4-4e16-8c4a-22a0fff7564f",
                            Manufacturer = "Land Rover",
                            StartingBid = 6549m,
                            Year = 2002,
                            LoadCapacity = 12288
                        },
                        new
                        {
                            Id = new Guid("2b22aa11-ebf0-464c-be6b-0c7cfb0c8364"),
                            Identifier = "c78a8292-dec0-44bc-9631-794f662a27f9",
                            Manufacturer = "BMW",
                            StartingBid = 20486m,
                            Year = 1984,
                            LoadCapacity = 30691
                        },
                        new
                        {
                            Id = new Guid("f0332a9b-1378-4ea7-809a-6eeab707f1e6"),
                            Identifier = "86020906-4982-49ff-8276-2fd382829007",
                            Manufacturer = "Dodge",
                            StartingBid = 13815m,
                            Year = 1983,
                            LoadCapacity = 32321
                        },
                        new
                        {
                            Id = new Guid("e1e2c722-e2f7-45c2-b3d0-914c364c2dc6"),
                            Identifier = "698f8517-b341-448f-98c2-e8b405f494c8",
                            Manufacturer = "Chevrolet",
                            StartingBid = 14063m,
                            Year = 1997,
                            LoadCapacity = 12447
                        });
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Bid", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Hatchback", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Hatchback", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Sedan", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Sedan", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Suv", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Suv", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Truck", b =>
                {
                    b.HasOne("CarAuction.Domain.Entities.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("CarAuction.Domain.Entities.Truck", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarAuction.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
